### ISSUE TITLE
Could not build Android app

### ISSUE THREAD

**Issue by bpcuong2013** [auctifera-josed/starprnt#15]
When I run the command, it gives me an error. The correct path of config.xml is /Volumes/WIN/ResearchProjs/StarprntDemoV2/platforms/android/app/src/main/res/xml/config.xml

$ ionic cordova build android
> cordova build android
cp: copyFileSync: could not write to dest file (code=ENOENT):/Volumes/WIN/ResearchProjs/StarprntDemoV2/platforms/android/res/xml/config.xml

(node:83779) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. (Parsing /Volumes/WIN/ResearchProjs/StarprntDemoV2/platforms/android/res/xml/config.xml failed)
    at EventEmitter.emit (events.js:141:19)
    at EventEmitter.module.exports.emit (/usr/local/lib/node_modules/cordova/node_modules/cordova-common/src/events.js:71:17)
    at EventEmitter.module.exports.emit (/Volumes/WIN/ResearchProjs/StarprntDemoV2/platforms/android/cordova/node_modules/cordova-common/src/events.js:68:30)
    at new ConfigParser (/Volumes/WIN/ResearchProjs/StarprntDemoV2/platforms/android/cordova/node_modules/cordova-common/src/ConfigParser/ConfigParser.js:34:16)
    at updateConfigFilesFrom (/Volumes/WIN/ResearchProjs/StarprntDemoV2/platforms/android/cordova/lib/prepare.js:106:18)
    at Api.module.exports.prepare (/Volumes/WIN/ResearchProjs/StarprntDemoV2/platforms/android/cordova/lib/prepare.js:42:20)
    at Api.prepare (/Volumes/WIN/ResearchProjs/StarprntDemoV2/platforms/android/cordova/Api.js:192:45)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/prepare.js:106:36
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
(node:83779) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:83779) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

----------------------------
$ cordova -v
8.0.0
$ ionic -v
3.20.0
$ npm -v
6.0.0
$ cordova platform list
Installed platforms:
  android 7.1.0
Available platforms: 
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0

**Comment by infoxicator** [comment]
The directory structure of Cordova android has changed on the latest version that might be the reason.
