### ISSUE TITLE
Android 31 hangs on never-ending printer search

### ISSUE THREAD

**Issue by igorsantos07** [auctifera-josed/starprnt#61]
Not going to explain how to reproduce this since, given the log I got from `logcat` in Android Studio below, it's probably happening in any app targeting API 31+ 

>java.lang.IllegalArgumentException: com.package.name: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
>Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
>
>at android.app.PendingIntent.checkFlags(PendingIntent.java:378)
>at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:648)
>at android.app.PendingIntent.getBroadcast(PendingIntent.java:635)
>at starprnt.cordova.StarPRNT.initialize(StarPRNT.java:114)

**Comment by igorsantos07** [comment]
lol this is actually a bug on the code we wrote on our own fork to request the permissions the plugin never did
